### ISSUE TITLE
Make "platform_directives" configuration easier and more readable

### ISSUE THREAD

**Issue by filiph** [dart-lang/angular2#114]
In order to get `*ngIf`, `*ngFor`, `*ngSwitch` and other directives by default (automatically declared in all components), you currently do this in `pubspec.yaml`:

```
transformers:
  angular2:
    platform_directives:
      - 'package:angular2/common.dart#CORE_DIRECTIVES'
      - 'package:angular2/common.dart#FORM_DIRECTIVES'
```

This seems arcane. I'd love to see this instead:

```
transformers:
  angular2:
    default_directives: [NgIf, NgFor, NgSwitch]
```

It's more explicit, less 'magic', and closer to what you'd do in a dart file.
