### ISSUE TITLE
Pub transformers hang on initial "pub get"

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular2#129]
Reproduction steps, at least for me:

`Dart VM version: 1.20.0-dev.10.3 (Wed Oct 12 10:53:42 2016) on "macos_x64"`

1. Clone angular2
2. Run `pub get --verbose`
3. Observe a hang:

```bash
FINE: [Fine from TemplateCompiler]:
    | [createCompileData] took 53 ms on angular2|lib/src/router/directives/router_outlet.ng_meta.json
```

It's not clear to me how to resolve this.

/cc @kevmoo for triage.

**Comment by jakemac53** [comment]
`pub get` runs transformers on things it knows it can ahead of time and caches the output. It looks like the transformer is hanging? I wouldn't expect it to be running the transformer on the current package though.....

**Comment by matanlurey** [comment]
@jakemac53:

https://github.com/dart-lang/angular2/blob/master/pubspec.yaml#L33

```yaml
transformers:
  - test/pub_serve:
      $include: test/**_test.dart
  - angular2/transform/codegen
```
