### ISSUE TITLE
Angular RC-18 transformer cannot coexist with Polymer RC-18 transformer

### ISSUE THREAD

**Issue by montyr75** [dart-lang/angular2#15]
Not sure whose issue this really is, but it was with the new release of Angular that the problem appeared. In a new Angular 2 project on Windows 10 and Dart SDK 1.17.1, with a pubspec like so:

```
dependencies:
  angular2: 2.0.0-beta.18
  polymer: ^1.0.0-rc.18
  web_components: ^0.12.0
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
transformers:
- polymer:
    entry_points: web/index.html
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter
```

A build error will occur. Pub Serve reports:
```
Build error:
Transform WebComponents on test_angular|web/index.html threw error: Invalid argument(s): Illegal character in path
dart:core/uri.dart 861                                  Uri._checkWindowsPathReservedCharacters
dart:core/uri.dart 962                                  Uri._makeWindowsFileUrl
dart:core/uri.dart 744                                  Uri.Uri.file
package:analyzer/src/string_source.dart 30:45           StringSource.StringSource
package:dart_style/src/dart_formatter.dart 81:28        DartFormatter.formatSource
package:dart_style/src/dart_formatter.dart 62:12        DartFormatter.format
package:initialize/transformer.dart 340:32              _BootstrapFileBuilder._buildNewEntryPoint
package:initialize/transformer.dart 225:49              _BootstrapFileBuilder.run
package:initialize/transformer.dart 37:8                generateBootstrapFile
package:web_components/build/web_components.dart 32:29  generateWebComponentsBootstrap
package:web_components/build/web_components.dart 82:25  WebComponentsTransformer.apply.<fn>.<fn>
dart:async/zone.dart 1204                               _RootZone.runUnary
dart:async/future_impl.dart 131                         _FutureListener.handleValue
dart:async/future_impl.dart 637                         _Future._propagateToListeners.handleValueCallback
dart:async/future_impl.dart 667                         _Future._propagateToListeners
dart:async/future_impl.dart 477                         _Future._completeWithValue
dart:async/future_impl.dart 528                         _Future._asyncComplete.<fn>
dart:async/schedule_microtask.dart 41                   _microtaskLoop
dart:async/schedule_microtask.dart 50                   _startMicrotaskLoop
dart:isolate-patch/isolate_patch.dart 96                _runPendingImmediateCallback
dart:isolate-patch/isolate_patch.dart 149               _RawReceivePortImpl._handleMessage
```

With Angular RC-17, this is not a problem.
