### ISSUE TITLE
How to use SASS with components?

### ISSUE THREAD

**Issue by bjesuiter** [dart-lang/angular2#154]
Hey Guys, 
I would like to now how to use SASS to "inject" styles from outside the shadow Dom view into the component. @matanlurey  - you wanted to provide some little examples how to do this with mixins when I asked you at dart dev summit ;)

**Comment by matanlurey** [comment]
Sure! Here is an example of the type of theming we do internally today:

Assume `material_button.scss`:

```scss
@mixin button-color($selector, $color, $hover-color: $color) {
  polyfill-unscoped-rule {
    color: $color;
    content: '#{$selector} > .content';
  }

  polyfill-unscoped-rule {
    color: $hover-color;
    content: '#{$selector}:hover > .content';
  }

  polyfill-unscoped-rule {
    color: rgba($color, .26);
    content: '#{$selector}.is-disabled > .content ';
  }
}
```

Then for usage, you would put in your `style.scss` (global styles):

```scss
@import 'path/to/material_button.scss';

@include button-color($selector: '*', $color: red, $hover-color: blue);
```

We should have something published on this in the next release of the Angular components.

/cc @filiph
