### ISSUE TITLE
Remove dart:mirrors dependency

### ISSUE THREAD

**Issue by dentra** [dart-lang/angular2#157]
`pub build` warn me about dart:mirrors dependency

```
...
* Your app imports dart:mirrors via:
*   main.template.dart => package:myPrj => package:angular2 => dart:mirrors
*   main.dart => package:myPrj => package:angular2 => dart:mirrors
...
```

I know that `angular` have transformer which removes refclection but maby you miss something.

**Comment by matanlurey** [comment]
Can I see your pubspec.yaml, if possible? You do need the reflection remover setup correctly to avoid using `dart:mirrors`. See https://github.com/dart-lang/angular2/wiki/Transformer#common-transformer-parameters and https://github.com/matanlurey/angular2_api_examples/blob/master/testing/pubspec.yaml#L25 for an example.

**Comment by dentra** [comment]
I am trying to add `angular2/transform/reflection_remover` manually but with no luck.

```yaml
name: umms
version: 0.0.1
environment:
  sdk: '>=1.20.0 <2.0.0'
dependencies:
  angular2: 2.0.0
  polymer: ^1.0.0-rc.18
  polymer_elements: ^1.0.0-rc.9
  web_components: ^0.12.3
  dart_to_js_script_rewriter: ^1.0.1
  browser: ^0.10.0
  meta: any
  logging: any
  dartson: any
  custom_elements: ^0.0.9+1
dependency_overrides:
# due to https://github.com/dart-lang/polymer-dart/issues/716
  analyzer: 0.29.0
dev_dependencies:
  test: ^0.12.15+8
publish_to:
  none
transformers:
  - dartson
  - polymer:
      entry_points: web/index.html
#  - angular2:
#      platform_directives:
#        - 'package:angular2/common.dart#COMMON_DIRECTIVES'
#        - 'package:umms/common/directives.dart#routerDirectives'
#        - 'package:umms/common/directives.dart#polymerDirectives'
#      platform_pipes:
#        - 'package:umms/common/pipes.dart#commonPipes'
#      entry_points:
#        - web/main.dart
  - angular2/transform/codegen:
      platform_directives:
        - 'package:angular2/common.dart#COMMON_DIRECTIVES'
        - 'package:umms/common/directives.dart#routerDirectives'
        - 'package:umms/common/directives.dart#polymerDirectives'
      platform_pipes:
        - 'package:umms/common/pipes.dart#commonPipes'
  - angular2/transform/reflection_remover:
      $include:
        - web/main.dart
  - $dart2js:
      $include: '**/*.bootstrap.initialize.dart'
      minify: true
      verbose: false
      commandLineOptions:
        - --trust-type-annotations
        - --trust-primitives
        - --dump-info
  - dart_to_js_script_rewriter
```

**Comment by jodinathan** [comment]
this is my pubspec and I have the same problem:


dependencies:
  browser: any
  angular2: ^2.2.0
  dart_to_js_script_rewriter: ^1.0.2
  http: ^0.11.3+9
  stack_trace: any
  uuid: any
  jsonp: any

dev_dependencies:
#  unittest: any

transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    - 'package:angular2/common.dart#FORM_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
    resolved_identifiers:
        BrowserClient: 'package:http/browser_client.dart'
        Client: 'package:http/http.dart'
- angular2/transform/reflection_remover:
    $include:
        - web/main.dart
- $dart2js:
    $include: 'web/main.dart'
    minify: true
    verbose: false
    #commandLineOptions:
     #   - --trust-type-annotations
      #  - --trust-primitives
       # - --dump-info
- dart_to_js_script_rewriter

What can I do to prevent using mirrors?

**Comment by zoechi** [comment]
@jodinathan AFAIK it's safe to ignore this warning

You can add
```yml
- $dart2js:
    commandLineOptions:
    - --enable-experimental-mirrors
```
to get rid of the warning.
If you're not using mirrors yourself it's probably because of `package:http/http.dart`

They only use some trick to make the same code work in browser and server but don't actually use mirrors in the implementation and it shouldn't cause code bloat.
The want to change that but that's blocked on an SDK issue https://github.com/dart-lang/http/issues/22#issuecomment-285500437
