### ISSUE TITLE
Error about index.html from a path dependency

### ISSUE THREAD

**Issue by zoechi** [dart-lang/angular2#215]
In Angular 2.1.1 I 
```
Pub Serve terminated
/usr/local/bin/dart/dart-sdk/bin/pub serve web --port=46683
Loading source assets...
Loading sass, test/pub_serve and dart_to_js_script_rewriter transformers...
Serving bwu_ng_mdl web on http://localhost:46683
[web] GET index.html => Could not find asset bwu_ng_mdl|web/index.html.
```

The project `bwu_ng_mdl` doesn`t even have an `angular2` transformer configured.
Only renaming `web` helped to fix that error.
`bwu_ng_mdl` is a path dependency.

The transformer configuration of the current project is

```
transformers:
- sass
- angular2:
    mirror_mode: verbose
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points:
    - web/index.dart
    resolved_identifiers:
        BrowserClient: 'package:http/browser_client.dart'
        BaseClient: 'package:http/http.dart'
        FhirConnection: 'package:fhir_client_api/fhir_client_api.dart'
        ResourceFactory: 'package:fhir_client_api/fhir_client_api.dart'
```
