### ISSUE TITLE
dom_renderer.dart is missing since version 2.1.0

### ISSUE THREAD

**Issue by stephan-gruen** [dart-lang/angular2#217]
I'm on Windows 7 /WebStorm 2016.3.1
All works perfect with version 2.0.0, but in version 2.1.0 a file seems to be missing. Same with version 2.1.1

```
[web] GET index.html => (cached) test|web/index.html
[web] GET packages/angular2/src/platform/dom/dom_renderer.dart => Could not find asset angular2|lib/src/platform/dom/dom_renderer.dart.
[web] GET Served 213 cached assets.
[web] GET Served 194 cached assets.
```

The file "dom_renderer.dart" is really missing from the folder "Cache\hosted\pub.dartlang.org\angular2-2.1.0\lib\src\platform\dom".
It is present in the folder "Cache\hosted\pub.dartlang.org\angular2-2.0.0\lib\src\platform\dom". 
Copying the file to the 2.1.0 folder does not solve the problem. 

```
yaml:
name: test
description: A Dart app that uses Angular 2
version: 0.0.1
environment:
  sdk: '>=1.19.0 <2.0.0'
dependencies:
  angular2: ^2.1.0
dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  angular2_components:
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter
```

Working dir: C:\Users\Stephan\dart\Angular2\test
D:\dart\dartium-1.21.0-dev.9.0\dart-sdk\bin\pub.bat cache repair
Downloading analyzer 0.29.0...
Downloading angular2 2.1.0...
Downloading angular2_components 0.1.1...
Downloading args 0.13.7...
Downloading async 1.11.3...
Downloading barback 0.15.2+9...
Downloading browser 0.10.0+2...
Downloading build 0.4.1+3...
Downloading charcode 1.1.1...
Downloading cli_util 0.0.1+2...
Downloading code_transformers 0.5.0+1...
Downloading collection 1.9.1...
Downloading convert 2.0.1...
Downloading crypto 2.0.1...
Downloading csslib 0.13.2+2...
Downloading dart_style 0.2.11+1...
Downloading dart_to_js_script_rewriter 1.0.2...
Downloading fixnum 0.10.5...
Downloading glob 1.1.3...
Downloading html 0.13.0...
Downloading http_parser 3.0.3...
Downloading intl 0.14.0...
Downloading isolate 0.2.3...
Downloading js 0.6.1...
Downloading logging 0.11.3+1...
Downloading matcher 0.12.0+2...
Downloading meta 1.0.4...
Downloading mime 0.9.3...
Downloading observable 0.14.0+1...
Downloading package_config 1.0.0...
Downloading path 1.4.0...
Downloading perf_api 0.1.0...
Downloading plugin 0.2.0...
Downloading pool 1.2.4...
Downloading protobuf 0.5.3...
Downloading quiver 0.23.0...
Downloading shelf 0.6.7+1...
Downloading shelf_static 0.2.4...
Downloading source_maps 0.10.1+2...
Downloading source_span 1.3.0...
Downloading stack_trace 1.7.0...
Downloading stream_channel 1.5.0...
Downloading string_scanner 1.0.1...
Downloading typed_data 1.1.3...
Downloading utf 0.9.0+3...
Downloading uuid 0.5.3...
Downloading watcher 0.9.7+3...
Downloading when 0.2.0...
Downloading which 0.1.3...
Downloading yaml 2.1.12...
Reinstalled 50 packages.
Process finished with exit code 0
