### ISSUE TITLE
Remove `PLATFORM_*` (directives|pipes) from AngularDart

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular2#363]
This is a formal intent to deprecate (3.X) and remove the `PLATFORM_*` flags from AngularDart.

i.e. the following pattern:

```yaml
transformers:
    - angular2:
        platform_directives:
            - 'package:angular2/common.dart#COMMON_DIRECTIVES'
        platform_pipes:
            - 'package:angular2/common.dart#COMMON_PIPES'
```

Would no longer function in AngularDart `4.0.0`.

## Background

Originally, these flags were used to reduce code duplication across modules, as it implicitly added `directives: const [ ... ]` and `pipes: const [ ... ]` into your entire compile process. However, this _greatly_ complicates the compile process, and actually only worked properly with `barback`.

In AngularDart 4.0.0+, we'll be experimenting with alternative ways to compile AngularDart, including keeping support for `barback` (pub transformers), but also future Dart build tools, and [bazel](https://bazel.build) support. Both of the latter tool sets cannot support this feature - they are modular compilers that can't resolve global application flags well.

## New compiler

In 3.1+, we'll have a flag to use a brand new compiler, name pending (but internally we refer to it as the "strong compiler". It uses Dart analysis summaries - metadata produced and used by the analyzer for IntelliJ, DartDevCompiler, and more - and it means we are able to finally solve the following:

* https://github.com/dart-lang/angular2/issues/10
* https://github.com/dart-lang/angular2/issues/19
* https://github.com/dart-lang/angular2/issues/153
* https://github.com/dart-lang/angular2/issues/158
* https://github.com/dart-lang/angular2/issues/218
* https://github.com/dart-lang/angular2/issues/231
* https://github.com/dart-lang/angular2/issues/245
* https://github.com/dart-lang/angular2/issues/288
* https://github.com/dart-lang/angular2/issues/291

And probably more I missed. I think we can all agree it's worth the compromise 😁
