### ISSUE TITLE
problem when upgrading existing project from 2.2.0 to 3.0.0

### ISSUE THREAD

**Issue by DanielTal** [dart-lang/angular2#370]
We have an existing project we started with angular2 2.2.0 
When moving to angular2 3.0.0, 
after upgrading also the rest depended packages, 
analyzer-0.30.0
angular2_components-0.5.0
build-0.8.0
csslib-0.13.5
func-1.0.0
We still get the following error in the pub get command

"Could not find asset angular2|lib/src/compiler/logging.dart"

below our pubspec.yaml file
```
environment:
  sdk: '>=1.21.0 <2.0.0'
dependencies:
  angular2: "^3.0.0"
  angular2_components: "^0.5.0"
  intl: ^0.14.0
  font_awesome: any
  json_object: any
dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  semantic_ui_angular_dart:
  bootstrap:
  event_bus: 
analyzer:
  strong-mode: true
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
    resolved_identifiers:
      BrowserClient: 'package:http/browser_client.dart'    
      Client: 'package:http/http.dart'
- dart_to_js_script_rewriter
```
