### ISSUE TITLE
Angular Dart transformer silently ignores `entry_points` files that do not exist

### ISSUE THREAD

**Issue by chalin** [dart-lang/angular2#38]
Consider the following excerpt from a `pubspec.yaml`:
```yaml
...
transformers:
- angular2:
    platform_directives: ...
    platform_pipes: ...
    entry_points: SOME/FILE_DOES_NOT_EXIST.dart
```

**Current behavior**
Running `pub serve` reports no error (but then fails to identify target types for static code generation), and so the app usually fails later down the road.

**Expected/desired behavior**
It would be nice if the transformer would at least report an error or warning if the `entry_points` do not exist.

* **Angular version:** 2.0.0-beta.17
* **Browser:** Chrome 50 | Chromium 45 
* **Language:** Dart

Migrated from https://github.com/angular/angular/issues/8897.
