### ISSUE TITLE
angular2 transformer: drop pubspec `entry_points`, use `@AngularEntrypoint()`

### ISSUE THREAD

**Issue by chalin** [dart-lang/angular2#412]
@matanlurey Given the cleanup that is being done in the pubspec entries for the `angular2` tranformer (such as #363, _Remove `PLATFORM_*` (directives|pipes) from AngularDart_), why not also consider dropping `entry_points` in favor of using an `@AngularEntrypoint()` annotation?

I.e. replace `entry_points` in
```yaml
transformers:
- angular2:
    entry_points: web/main.dart
```
with use of the annotation as in
```dart
@AngularEntrypoint()
void main() {
  bootstrap(AppComponent);
}
```

cc @kwalrath
