### ISSUE TITLE
In beta.21 I get an error about a missing entry points configured in a dependency

### ISSUE THREAD

**Issue by zoechi** [dart-lang/angular2#64]
```
Pub Serve terminated
/usr/local/bin/dart/dart-sdk/bin/pub serve test --port=42943
Loading source assets...
Loading sass, angular2 and dart_to_js_script_rewriter transformers...
The value "web/index.dart" in "entry_points" of the Angular 2 transformer configuration does not point to any file.
Error on line 24, column 5 of ../../../contributing/ng_bootstrap/pubspec.yaml: Error loading transformer: Directory listing failed, path = './web/components/accordion/' (OS Error: No such file or directory, errno = 2)
    platform_directives:
    ^^^^^^^^^^^^^^^^^^^^^
Pub Serve terminated
```

pubspec.yaml

```
dependencies:
  angular2: ^2.0.0-beta.19
  bootstrap_sass: 4.0.0-alpha.2
  browser: ^0.10.0+2
  http: ^0.11.3+9
  meta: '^1.0.1'
  ng_bootstrap: #^0.1.0
    path: ../../../contributing/ng_bootstrap

transformers:
- sass
- angular2:
    mirror_mode: verbose
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points:
    - web/main.dart
    - test/webui/primitive_value_input/string_input_test.dart
    resolved_identifiers:
        BrowserClient: 'package:http/browser_client.dart'
...
```

I don't get why the Angular2 transformer reads `entry_points` from a dependency.
